import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import { Toaster } from "@/components/DashboardCompoenents/ui/toaster";
import NavbarConpoenent from "@/components/UserPage/Navbar/NavbarConpoenent";
import Footer from "@/components/UserPage/Footer/Footer";
import FloatingButtons from "@/hooks/FloatingButton";
import { Inter, Suwannaphum } from "next/font/google";
import StoreProvider from "../StoreProvider";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});
const suwannaphum = Suwannaphum({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["khmer"],
  display: "swap",
  variable: "--font-suwannaphum",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning className={` ${suwannaphum.variable} ${inter.variable}`}>
        <StoreProvider>

          <div className="flex min-h-screen">
            <div className="w-full bg-white dark:bg-[#020d1a]">
              <NavbarConpoenent />

              <main className="isolate mx-auto w-full max-w-screen-3xl">
                {children}
                <FloatingButtons />
              </main>

              <Footer />
            </div>
          </div>

          <Toaster />

        </StoreProvider>
      </body>
    </html>
  );
}

