import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Providers } from "../providers";
import { Sidebar } from "@/components/DashboardCompoenents/Layouts/sidebar";
import { Header } from "@/components/DashboardCompoenents/Layouts/header";
import { Toaster } from "@/components/DashboardCompoenents/ui/toaster";
import FloatingButtons from "@/hooks/FloatingButton";
import StoreProvider from "../StoreProvider";
import { SidebarProvider } from "@/components/DashboardCompoenents/Layouts/sidebar/sidebar-context";
import RoleGuard from "../RoleGuard";
import { Inter, Suwannaphum } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import AiKimla from "@/hooks/AiKimla";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});
const suwannaphum = Suwannaphum({
  weight: ["100", "300", "400", "700", "900"],
  subsets: ["khmer"],
  display: "swap",
  variable: "--font-suwannaphum",
});

export default async function LocalLayout({
  children,

}: Readonly<{
  children: React.ReactNode;

}>) {





  return (

    <html lang="en" suppressHydrationWarning >
      <body suppressHydrationWarning className={` ${suwannaphum.variable} ${inter.variable}`} >
       
        <StoreProvider>
           <RoleGuard>
          {/* Wrap everything inside the body to ensure context is available everywhere */}
          <SidebarProvider>
            <div className="flex min-h-screen">
              <Sidebar />
              <div className="flex flex-1 flex-col min-w-0 bg-gray-2 dark:bg-[#020d1a] transition-all duration-300">
                <Header />
                <main className="mx-auto w-full max-w-screen-2xl p-4 md:p-7.5">
                  {children}
                  <AiKimla />
                </main>
              </div>
            </div>
            <Toaster />
          </SidebarProvider>
          </RoleGuard>
        </StoreProvider>
       
      </body>
      
    </html>

  );
}
